### ISSUE TITLE
Nerdesin?

### ISSUE THREAD

**Issue by inoshell** [MarqEMain/x#1]
Sana discorddan ulaşamıyoruz. inoaa#0544 lütfen dön.

**Comment by MarqEMain** [comment]
> Sana discorddan ulaşamıyoruz. inoaa#544 lütfen dön.

e tag yanlış.

**Comment by inoshell** [comment]
inoaa#0544 şimdi oldu sanırm

**Comment by inoshell** [comment]
> inoaa#544 şimdi oldu sanırm

544'den önce 0 var.
